-- MySQL Script generated by MySQL Workbench
-- 03/30/16 18:48:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `type` INT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Laboratory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Laboratory` (
  `idLaboratory` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idLaboratory`, `User_idUser`),
  INDEX `fk_Laboratory_User_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Laboratory_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Laboratory_Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Laboratory_Schedule` (
  `timeStart` TIME NULL,
  `timeEnd` TIME NULL,
  `day` VARCHAR(45) NULL,
  `Laboratory_idLaboratory` INT NOT NULL,
  PRIMARY KEY (`Laboratory_idLaboratory`),
  CONSTRAINT `fk_Laboratory_Schedule_Laboratory1`
    FOREIGN KEY (`Laboratory_idLaboratory`)
    REFERENCES `mydb`.`Laboratory` (`idLaboratory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pharmacy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pharmacy` (
  `idLaboratory` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idLaboratory`, `User_idUser`),
  INDEX `fk_Pharmacy_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Pharmacy_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pharmacy_Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pharmacy_Schedule` (
  `timeStart` TIME NULL,
  `timeEnd` TIME NULL,
  `day` VARCHAR(45) NULL,
  `Pharmacy_idLaboratory` INT NOT NULL,
  PRIMARY KEY (`Pharmacy_idLaboratory`),
  CONSTRAINT `fk_Pharmacy_Schedule_Pharmacy1`
    FOREIGN KEY (`Pharmacy_idLaboratory`)
    REFERENCES `mydb`.`Pharmacy` (`idLaboratory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Presentation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Presentation` (
  `idPresentation` INT NOT NULL,
  `unitPresentation` VARCHAR(45) NULL,
  `quantityPresentation` VARCHAR(45) NULL,
  PRIMARY KEY (`idPresentation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medicine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medicine` (
  `idMedicine` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `price` VARCHAR(45) NULL,
  PRIMARY KEY (`idMedicine`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medicine_has_Presentation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medicine_has_Presentation` (
  `Medicine_idMedicine` INT NOT NULL,
  `Presentation_idPresentation` INT NOT NULL,
  PRIMARY KEY (`Medicine_idMedicine`, `Presentation_idPresentation`),
  INDEX `fk_Medicine_has_Presentation_Presentation1_idx` (`Presentation_idPresentation` ASC),
  CONSTRAINT `fk_Medicine_has_Presentation_Medicine1`
    FOREIGN KEY (`Medicine_idMedicine`)
    REFERENCES `mydb`.`Medicine` (`idMedicine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medicine_has_Presentation_Presentation1`
    FOREIGN KEY (`Presentation_idPresentation`)
    REFERENCES `mydb`.`Presentation` (`idPresentation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medicine_has_Laboratory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medicine_has_Laboratory` (
  `Laboratory_Schedule_Laboratory_idLaboratory` INT NOT NULL,
  `Medicine_idMedicine` INT NOT NULL,
  PRIMARY KEY (`Laboratory_Schedule_Laboratory_idLaboratory`, `Medicine_idMedicine`),
  INDEX `fk_Medicine_has_Laboratory_Medicine1_idx` (`Medicine_idMedicine` ASC),
  CONSTRAINT `fk_Medicine_has_Laboratory_Laboratory_Schedule1`
    FOREIGN KEY (`Laboratory_Schedule_Laboratory_idLaboratory`)
    REFERENCES `mydb`.`Laboratory_Schedule` (`Laboratory_idLaboratory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medicine_has_Laboratory_Medicine1`
    FOREIGN KEY (`Medicine_idMedicine`)
    REFERENCES `mydb`.`Medicine` (`idMedicine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pharmacy_has_Medicine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pharmacy_has_Medicine` (
  `Pharmacy_Schedule_Pharmacy_idLaboratory` INT NOT NULL,
  `Medicine_idMedicine` INT NOT NULL,
  PRIMARY KEY (`Pharmacy_Schedule_Pharmacy_idLaboratory`, `Medicine_idMedicine`),
  INDEX `fk_Pharmacy_has_Medicine_Medicine1_idx` (`Medicine_idMedicine` ASC),
  CONSTRAINT `fk_Pharmacy_has_Medicine_Pharmacy_Schedule1`
    FOREIGN KEY (`Pharmacy_Schedule_Pharmacy_idLaboratory`)
    REFERENCES `mydb`.`Pharmacy_Schedule` (`Pharmacy_idLaboratory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pharmacy_has_Medicine_Medicine1`
    FOREIGN KEY (`Medicine_idMedicine`)
    REFERENCES `mydb`.`Medicine` (`idMedicine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
