-- MySQL Script generated by MySQL Workbench
-- 02/21/16 20:22:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema FarmaPro_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FarmaPro_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FarmaPro_DB` DEFAULT CHARACTER SET utf8 ;
USE `FarmaPro_DB` ;

-- -----------------------------------------------------
-- Table `FarmaPro_DB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FarmaPro_DB`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(60) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `type` INT NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FarmaPro_DB`.`Pharmacy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FarmaPro_DB`.`Pharmacy` (
  `idPharmacy` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `timeStart` TIME NULL,
  `timeEnd` TIME NULL,
  `day` VARCHAR(45) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idPharmacy`, `User_idUser`),
  INDEX `fk_Pharmacy_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Pharmacy_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `FarmaPro_DB`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FarmaPro_DB`.`Laboratory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FarmaPro_DB`.`Laboratory` (
  `idLaboratory` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `timeStart` TIME NULL,
  `timeEnd` TIME NULL,
  `day` VARCHAR(45) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idLaboratory`, `User_idUser`),
  INDEX `fk_Laboratory_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Laboratory_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `FarmaPro_DB`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FarmaPro_DB`.`Medicine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FarmaPro_DB`.`Medicine` (
  `idMedicine` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `price` INT NULL,
  `Laboratory_idLaboratory` INT NOT NULL,
  PRIMARY KEY (`idMedicine`, `Laboratory_idLaboratory`),
  INDEX `fk_Medicine_Laboratory1_idx` (`Laboratory_idLaboratory` ASC),
  CONSTRAINT `fk_Medicine_Laboratory1`
    FOREIGN KEY (`Laboratory_idLaboratory`)
    REFERENCES `FarmaPro_DB`.`Laboratory` (`idLaboratory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FarmaPro_DB`.`Administration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FarmaPro_DB`.`Administration` (
  `idAdministration` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `shape` VARCHAR(45) NULL,
  PRIMARY KEY (`idAdministration`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FarmaPro_DB`.`Presentation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FarmaPro_DB`.`Presentation` (
  `idPresentation` INT NOT NULL,
  `unitPresentation` VARCHAR(45) NULL,
  `quantityPresentation` VARCHAR(45) NULL,
  `idAdministration` INT NOT NULL,
  `Medicine_idMedicine` INT NOT NULL,
  `Medicine_Laboratory_idLaboratory` INT NOT NULL,
  PRIMARY KEY (`idPresentation`, `idAdministration`, `Medicine_idMedicine`, `Medicine_Laboratory_idLaboratory`),
  INDEX `fk_Presentation_Administration_idx` (`idAdministration` ASC),
  INDEX `fk_Presentation_Medicine1_idx` (`Medicine_idMedicine` ASC, `Medicine_Laboratory_idLaboratory` ASC),
  CONSTRAINT `fk_Presentation_Administration`
    FOREIGN KEY (`idAdministration`)
    REFERENCES `FarmaPro_DB`.`Administration` (`idAdministration`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Presentation_Medicine1`
    FOREIGN KEY (`Medicine_idMedicine` , `Medicine_Laboratory_idLaboratory`)
    REFERENCES `FarmaPro_DB`.`Medicine` (`idMedicine` , `Laboratory_idLaboratory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FarmaPro_DB`.`Pharmacy_has_Medicine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FarmaPro_DB`.`Pharmacy_has_Medicine` (
  `idPharmacy` INT NOT NULL,
  `idMedicine` INT NOT NULL,
  PRIMARY KEY (`idPharmacy`, `idMedicine`),
  INDEX `fk_Pharmacy_has_Medicine_Medicine1_idx` (`idMedicine` ASC),
  INDEX `fk_Pharmacy_has_Medicine_Pharmacy1_idx` (`idPharmacy` ASC),
  CONSTRAINT `fk_Pharmacy_has_Medicine_Pharmacy1`
    FOREIGN KEY (`idPharmacy`)
    REFERENCES `FarmaPro_DB`.`Pharmacy` (`idPharmacy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pharmacy_has_Medicine_Medicine1`
    FOREIGN KEY (`idMedicine`)
    REFERENCES `FarmaPro_DB`.`Medicine` (`idMedicine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
